// web/src/components/ShareLinkButton.tsx
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
    Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, Stack, TextField, Tooltip, Typography,
} from '@mui/material';
import { QRCodeSVG } from 'qrcode.react';
import { useAppStore } from '@/stores/appStore';
import { useWebSocketStore } from '@/stores/wsStore';
import { toast } from '@/stores/toastStore';
import {
    SHARE_DEFAULT_TTL_MINUTES, SHARE_MAX_TTL_MINUTES, SHARE_MAX_USES_LIMIT, SHARE_MIN_TTL_MINUTES,
    buildCleanAbsoluteRouteUrl, copyTextToClipboard, formatShareDuration, formatTimestamp,
    minutesToShareTTL, normalizeShareMaxUses, normalizeShareTTL, withCurrentOrigin, withShareQrFlag,
} from '@/lib/util';
import { SHARE_TTL_PRESET_MINUTES, shareTtlProgress } from '@/lib/share-config.js';
import { createShareLink } from '@/services/share';
import { MdiIcon } from '@/components/ui/MdiIcon';
import type { ReceivedItem } from '@/stores/appStore';

/**
 * 分享：一个图标，一个面板 —— 从 web-vue3/src/components/ShareLinkButton.vue 移植。
 *
 * ⚠️ 「复制链接」与「二维码」产出的**是同一个 URL**（分享页地址），所以合成一条路径：
 * 点图标 →（可选：有效期/次数/密码设置框）→ 链接进剪贴板 + 弹出面板。
 * ⚠️ 两种形态：`iconOnly`（卡片图标，受 `display.cardShare` 管）/ 带文字（详情弹窗动作行，
 * **不受开关管** —— 那个开关叫「卡片图标」，只管卡片上那排图标）。
 */
export function ShareLinkButton({
    meta,
    iconOnly = true,
    className,
}: {
    meta: ReceivedItem;
    iconOnly?: boolean;
    className?: string;
}) {
    const { t } = useTranslation();
    const cardShare = useAppStore((s) => s.displayByMode[s.uiMode]?.cardShare ?? true);
    const shareDialogEnabled = useAppStore((s) => s.displayByMode[s.uiMode]?.shareDialog ?? true);
    const shareDefaults = useAppStore((s) => s.shareDefaults);
    const prefix = useAppStore((s) => s.config?.server?.prefix || '');
    const room = useWebSocketStore((s) => s.room);

    const [settingsOpen, setSettingsOpen] = useState(false);
    const [resultOpen, setResultOpen] = useState(false);
    const [loading, setLoading] = useState(false);
    const [shareUrl, setShareUrl] = useState('');
    const [form, setForm] = useState({ ttlMinutes: SHARE_DEFAULT_TTL_MINUTES, maxUses: 0, password: '' });

    // 兜底地址：服务端一律签发 token 并回分享页地址，只有在拿不到 url 时才用这条。
    const fallbackUrl = buildCleanAbsoluteRouteUrl(
        `content/${meta?.id ?? ''}${room ? `?room=${encodeURIComponent(room)}` : ''}`,
        prefix,
    );
    // 二维码里编的地址要比「复制到剪贴板的那条」多一个 q=1（扫码进来要能上报）。
    const qrUrl = withShareQrFlag(shareUrl || fallbackUrl);

    const ttlSeconds = minutesToShareTTL(form.ttlMinutes);
    const ttlLabel = formatShareDuration(ttlSeconds, (key: string, params?: Record<string, unknown>) => t(key, params as never));

    const copyToClipboard = async (value: string, successKey = 'copySuccess') => {
        try {
            await copyTextToClipboard(value);
            toast(t(successKey));
        } catch {
            toast(t('copyFailedGeneral'));
        }
    };

    const confirmShare = async () => {
        const ttl = normalizeShareTTL(ttlSeconds);
        const maxUses = normalizeShareMaxUses(form.maxUses);
        const password = String(form.password || '').trim();
        setLoading(true);
        try {
            const data = await createShareLink({ type: 'content', id: meta?.id, ttl, maxUses, password, room });
            // ⚠️ 主机名不能用服务端那份：它是按**请求的 Host** 拼的，中间只要有改写 Host 的代理就错
            // （dev 的 vite proxy 写了 changeOrigin: true）。换成浏览器自己的 origin，路径照原样保留。
            const url = withCurrentOrigin(data?.pageUrl) || withCurrentOrigin(data?.url) || fallbackUrl;
            setShareUrl(url);
            setSettingsOpen(false);
            setResultOpen(true);
            await copyToClipboard(url);
        } catch (error) {
            console.error('生成分享链接失败:', error);
            toast(t('copyFailedGeneral'));
        } finally {
            setLoading(false);
        }
    };

    const openShare = () => {
        // 「分享时弹出设置框」关掉时，直接用设置里存好的默认值建链接，不弹框。
        if (!shareDialogEnabled) {
            setForm({ ...shareDefaults });
            void confirmShare();
            return;
        }
        setForm({ ttlMinutes: SHARE_DEFAULT_TTL_MINUTES, maxUses: 0, password: '' });
        setSettingsOpen(true);
    };

    const button = iconOnly ? (
        <Tooltip title={t('shareLink')}>
            <IconButton size="small" className={className} onClick={(e) => { e.stopPropagation(); openShare(); }} aria-label={t('shareLink')}>
                <MdiIcon name="mdi-share-variant" size={18} />
            </IconButton>
        </Tooltip>
    ) : (
        <Button size="small" variant="text" className={className} startIcon={<MdiIcon name="mdi-share-variant" size={16} />} onClick={(e) => { e.stopPropagation(); openShare(); }}>
            {t('shareLink')}
        </Button>
    );

    if (iconOnly && !cardShare) {
        return null;
    }

    return (
        <>
            {button}

            <Dialog open={settingsOpen} onClose={() => setSettingsOpen(false)} maxWidth="xs" fullWidth>
                <DialogTitle>{t('shareLinkSettings')}</DialogTitle>
                <DialogContent>
                    <Typography variant="body2" color="text.secondary" sx={{ mb: 1.5 }}>{t('shareLinkSettingsHint')}</Typography>
                    <Stack direction="row" justifyContent="space-between" alignItems="center">
                        <Typography variant="subtitle2">{t('shareExpireIn')}</Typography>
                        <Typography variant="body2" color="primary" fontWeight={500}>{ttlLabel}</Typography>
                    </Stack>
                    <input
                        type="range"
                        min={SHARE_MIN_TTL_MINUTES}
                        max={SHARE_MAX_TTL_MINUTES}
                        step={1}
                        value={form.ttlMinutes}
                        aria-label={t('shareExpireIn')}
                        onChange={(e) => setForm((prev) => ({ ...prev, ttlMinutes: Number(e.target.value) }))}
                        style={{ width: '100%', margin: '8px 0' }}
                    />
                    <Stack direction="row" spacing={0.75} sx={{ mb: 1, flexWrap: 'wrap' }}>
                        {(SHARE_TTL_PRESET_MINUTES as number[]).map((minutes) => (
                            <Chip
                                key={minutes}
                                size="small"
                                label={formatShareDuration(minutesToShareTTL(minutes), (key: string, params?: Record<string, unknown>) => t(key, params as never))}
                                variant={form.ttlMinutes === minutes ? 'filled' : 'outlined'}
                                color={form.ttlMinutes === minutes ? 'primary' : 'default'}
                                onClick={() => setForm((prev) => ({ ...prev, ttlMinutes: minutes }))}
                            />
                        ))}
                    </Stack>
                    <div style={{ height: 6, borderRadius: 999, background: 'color-mix(in srgb, currentColor 18%, transparent)', marginBottom: 4 }}>
                        <div style={{ height: 6, borderRadius: 999, background: 'var(--mui-palette-primary-main)', width: `${shareTtlProgress(form.ttlMinutes)}%` }} />
                    </div>
                    <Stack direction="row" justifyContent="space-between" sx={{ mb: 2 }}>
                        <Typography variant="caption" color="text.secondary">{t('shareTtlMinLabel')}</Typography>
                        <Typography variant="caption" color="text.secondary">{t('shareTtlMaxLabel')}</Typography>
                    </Stack>
                    <TextField
                        fullWidth
                        size="small"
                        type="number"
                        label={t('shareMaxUses')}
                        helperText={t('shareMaxUsesHint')}
                        value={form.maxUses}
                        slotProps={{ htmlInput: { min: 0, max: SHARE_MAX_USES_LIMIT } }}
                        onChange={(e) => setForm((prev) => ({ ...prev, maxUses: Number(e.target.value) }))}
                        sx={{ mb: 2 }}
                    />
                    <TextField
                        fullWidth
                        size="small"
                        type="password"
                        autoComplete="new-password"
                        label={t('sharePasswordLabel')}
                        helperText={t('sharePasswordHint')}
                        value={form.password}
                        onChange={(e) => setForm((prev) => ({ ...prev, password: e.target.value }))}
                    />
                </DialogContent>
                <DialogActions>
                    <Button variant="text" onClick={() => setSettingsOpen(false)}>{t('cancel')}</Button>
                    <Button variant="text" color="primary" loading={loading} onClick={confirmShare}>{t('generateAndCopy')}</Button>
                </DialogActions>
            </Dialog>

            <Dialog open={resultOpen} onClose={() => setResultOpen(false)} maxWidth="xs" fullWidth>
                <DialogTitle sx={{ textAlign: 'center' }}>{t('shareLink')}</DialogTitle>
                <DialogContent sx={{ textAlign: 'center' }}>
                    <QRCodeSVG value={qrUrl} size={200} level="H" />
                    <Typography variant="caption" sx={{ display: 'block', mt: 1, wordBreak: 'break-all' }}>
                        {shareUrl || fallbackUrl}
                    </Typography>
                    <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 1 }}>
                        {t('shareOpenedTimes', { count: 0 })} · {t('shareOpenedHint')}
                    </Typography>
                    <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 0.5 }}>
                        {t('shareMetaSummary', {
                            expiresAtText: formatTimestamp(Math.floor(Date.now() / 1000) + ttlSeconds),
                            usesText: form.maxUses > 0 ? t('shareUsesLimited', { count: form.maxUses }) : t('shareUsesUnlimited'),
                        })}
                    </Typography>
                </DialogContent>
                <DialogActions>
                    <Button variant="text" color="primary" startIcon={<MdiIcon name="mdi-content-copy" size={16} />} onClick={() => copyToClipboard(shareUrl || fallbackUrl, 'copySuccess')}>
                        {t('copyLink')}
                    </Button>
                    <Button variant="text" onClick={() => setResultOpen(false)}>{t('close')}</Button>
                </DialogActions>
            </Dialog>
        </>
    );
}

// web-vue3/src/components/ShareLinkButton.vue
<script setup>
// 分享：一个图标，一个面板。
//
// 「复制链接」和「二维码」以前是两个图标，但它们产出的**是同一个 URL**（分享页地址），
// 区别只剩呈现方式 —— 拆成两个等于让用户先做一个没有意义的决定。现在合成一条路径：
// 点图标 →（可选：有效期/次数/密码设置框）→ 链接进剪贴板 + 弹出面板，
// 面板里二维码、链接、复制按钮、有效期/次数一次给全。
//
// 「默认展示格式」这个设置**故意没有**：分享页自己就带 raw↔md 切换，收件人当场就能换，
// 发送方再替他选一次是多余的一道决定（选错了收件人还得自己找按钮换回来）。
//
// 为什么收成一个组件：这段东西（图标 + 两个弹窗 + 有效期滑块的全部样式）以前在
// received-item/Text.vue 和 received-item/File.vue 里逐字节各存了一份 —— 改一处要改两处，
// 而且其余五个模式也要接同一个入口，再抄下去就是七份。
//
// 调用点两种形态：
//     <share-link-button :meta="meta" class="timeline-card__icon-button" />   ← 卡片图标
//     <share-link-button :meta="detailItem" :icon-only="false" />             ← 弹窗动作行
// 卡片形态是否显示由组件内部按 `app.display.cardShare` 判断，调用点不用管。
//
// ⚠️ 弹窗（v-dialog）一律 teleport 出应用子树，所以这里所有样式都必须挂在自己身上，
// 不能指望祖先的类或 CSS 变量（见仓库里那条覆盖层约定）。样式块因此是 scoped 的
// 本组件样式，而不是留在卡片里。
import { computed, ref } from 'vue';
import { useAppStore } from '@/store/app';
import { useWebSocketStore } from '@/store/websocket';
import { useI18n } from 'vue-i18n';
import { toast } from '@/plugins/toast';
import QrcodeVue from 'qrcode.vue';
import {
    SHARE_DEFAULT_TTL_MINUTES,
    SHARE_MAX_TTL_MINUTES,
    SHARE_MAX_USES_LIMIT,
    SHARE_MIN_TTL_MINUTES,
    buildCleanAbsoluteRouteUrl,
    copyTextToClipboard,
    createShareLink,
    formatShareDuration,
    formatTimestamp,
    minutesToShareTTL,
    normalizeShareMaxUses,
    normalizeShareTTL,
    withCurrentOrigin,
    withShareQrFlag,
} from '@/util.js';
import { SHARE_TTL_PRESET_MINUTES, shareTtlProgress as shareTtlPercent } from '@/share-config.js';

const mdiContentCopy = 'mdi-content-copy';
const mdiShareVariant = 'mdi-share-variant';

// 根节点不止一个（图标 + 两个弹窗），class 没法自动落到按钮上 —— 关掉继承，
// 在按钮上自己把 `$attrs` 展开进去，调用点才能照旧写 `class="..."`。
// ⚠️ 只能合成**一个** v-bind：同一元素上写两个 `v-bind="..."` 会被 SFC 解析器判成
// "Duplicate attribute"（`mergeProps` 那套是运行时行为，编译期先拦）。
// tooltip 的 activator 属性里只有事件和 `aria-describedby`、**没有 class**，
// 所以 `{ ...activatorProps, ...$attrs }` 不会互相覆盖。
defineOptions({ inheritAttrs: false });

const props = defineProps({
    meta: {
        type: Object,
        default: () => ({}),
    },
    // 两种形态，对应两种入口：
    //   true （默认）= 卡片右上角那排里的纯图标按钮，靠 `app.display.cardShare` 控制显隐；
    //   false       = 详情 / 阅读器弹窗动作行里的带文字按钮，**不受开关管** ——
    //                 那个开关叫「卡片图标」，只管卡片上那排图标（见 data/displayToggles.js）。
    iconOnly: {
        type: Boolean,
        default: true,
    },
});

const app = useAppStore();
const ws = useWebSocketStore();
const { t } = useI18n();

const shareResultVisible = ref(false);
const shareDialogVisible = ref(false);
const shareForm = ref({ ttlMinutes: SHARE_DEFAULT_TTL_MINUTES, maxUses: 0, password: '' });
const shareTtlMinMinutes = SHARE_MIN_TTL_MINUTES;
const shareTtlMaxMinutes = SHARE_MAX_TTL_MINUTES;
const shareUrlLoading = ref(false);
const shareContentUrl = ref('');
const lastShareMeta = ref(null);

// 兜底地址：服务端现在一律签发 token 并回分享页地址，只有在拿不到 `url` 时才用这条。
const contentUrl = computed(() => {
    const roomQuery = ws.room ? `?room=${encodeURIComponent(ws.room)}` : '';
    const id = props.meta?.id ?? '';
    return buildCleanAbsoluteRouteUrl(`content/${id}${roomQuery}`, app?.config?.server?.prefix || '');
});
// 二维码里编的地址要比「复制到剪贴板的那条」多一个 q=1 ——
// 扫码和点链接打开的是同一个页面，服务端分不出来，只有地址上带了这个参数，
// 分享页上报时才能告诉服务端「这次是扫过来的」。
// 复制出去的那条不带它（它本来就是点开的）。
// ⚠️ 分享地址是 `<prefix>/s/<token>`（**没有 `#`**），q=1 拼在普通 query 上，分享页用
// route.query.q 读它 —— 见 withShareQrFlag。
const shareQrUrl = computed(() => withShareQrFlag(shareContentUrl.value) || shareContentUrl.value);
const shareTtlSeconds = computed(() => minutesToShareTTL(shareForm.value.ttlMinutes));
const shareTtlLabel = computed(() => formatShareDuration(shareTtlSeconds.value, (key, params) => t(key, params)));
const shareTtlPresets = computed(() =>
    SHARE_TTL_PRESET_MINUTES.map((minutes) => ({
        minutes,
        label: formatShareDuration(minutesToShareTTL(minutes), (key, params) => t(key, params)),
    })),
);
const shareTtlProgress = computed(() => shareTtlPercent(shareForm.value.ttlMinutes));
function onShareTtlInput(event) {
    const next = Number(event && event.target ? event.target.value : shareForm.value.ttlMinutes);
    shareForm.value.ttlMinutes = Number.isFinite(next) ? next : SHARE_DEFAULT_TTL_MINUTES;
}
function openShareDialog() {
    // 「分享时弹出设置框」关掉时，直接用设置里存好的默认值建链接，不弹框。
    // 先把默认值灌进表单再走同一条确认路径 —— 这样两条路只有一个建链接的地方。
    if (!app.display.shareDialog) {
        shareForm.value = { ...app.shareDefaults };
        confirmShareDialog();
        return;
    }
    shareForm.value = {
        ttlMinutes: SHARE_DEFAULT_TTL_MINUTES,
        maxUses: 0,
        password: '',
    };
    shareDialogVisible.value = true;
}
async function copyShareLink() {
    if (shareContentUrl.value) {
        await copyToClipboard(shareContentUrl.value, 'copySuccess');
    }
}
async function confirmShareDialog() {
    const ttl = normalizeShareTTL(shareTtlSeconds.value);
    const maxUses = normalizeShareMaxUses(shareForm.value.maxUses);
    const password = String(shareForm.value.password || '').trim();
    shareUrlLoading.value = true;
    try {
        const data = await createShareLink({
            type: 'content',
            id: props.meta?.id,
            ttl,
            maxUses,
            password,
            room: ws.room,
        });
        // 分享给出去的是**分享地址本身**：`<prefix>/s/<token>`，token 在路径里。
        // 服务端把 OG 卡片注入 SPA 外壳后就发这一份，所以贴进微信 / Telegram 能展开预览，
        // 真人打开看到的也是分享页（前端路由 /s/:token 接管）—— 同一个地址，没有第二跳。
        // `url` 与 `pageUrl` 现在是同一个值（老服务端回来的 `url` 还是 hash 地址，所以两个都试）。
        //
        // ⚠️ 主机名照旧不能直接用：服务端是按**请求的 Host** 拼的，中间只要有改写 Host 的代理就错
        // —— dev 的 vite proxy 写了 `changeOrigin: true`，拼出来会指向后端。换成浏览器自己的
        // origin，路径照原样保留（所以带 prefix 部署也不会丢）。
        // 老服务端可能什么都不给：那时回落到本地拼的兜底地址。
        const url = withCurrentOrigin(data?.pageUrl) || withCurrentOrigin(data?.url) || contentUrl.value;
        shareContentUrl.value = url;
        lastShareMeta.value = {
            ttl: data?.ttl ?? ttl,
            maxUses: data?.maxUses ?? maxUses,
            expiresAtText: formatTimestamp(data?.expiresAt || (Math.floor(Date.now() / 1000) + ttl)),
            usesText: (data?.maxUses ?? maxUses) > 0
                ? t('shareUsesLimited', { count: data?.maxUses ?? maxUses })
                : t('shareUsesUnlimited'),
            // 刚建出来的链接当然是 0 次 —— 写出来不是废话：「0」说明统计是通的，
            // 之后想看累计就进「设置 → 分享记录」（那边读的是服务端的记录，会累加）。
            openedText: t('shareOpenedTimes', { count: data?.visits ?? 0 }),
        };
        shareDialogVisible.value = false;
        shareResultVisible.value = true;
        await copyToClipboard(url, 'copySuccess');
    } catch (error) {
        console.error('生成分享链接失败:', error);
        toast(t('copyFailedGeneral'));
    } finally {
        shareUrlLoading.value = false;
    }
}
async function copyToClipboard(textToCopy, successMessageKey = 'copySuccess', errorMessageKey = 'copyFailedGeneral') {
    try {
        await copyTextToClipboard(textToCopy);
        toast(t(successMessageKey));
    } catch (err) {
        console.error('复制失败:', err);
        toast(t(errorMessageKey));
    }
}
</script>

<template>
    <!-- 卡片图标形态：纯图标 + tooltip，受「卡片图标 → 分享链接」开关控制 -->
    <v-tooltip v-if="iconOnly && app.display.cardShare" :text="t('shareLink')" location="top">
        <template v-slot:activator="{ props: activatorProps }">
            <v-btn
                v-bind="{ ...activatorProps, ...$attrs }"
                icon
                density="compact"
                variant="text"
                color="grey"
                @click.stop="openShareDialog"
            >
                <v-icon>{{ mdiShareVariant }}</v-icon>
            </v-btn>
        </template>
    </v-tooltip>

    <!-- 弹窗动作行形态：图标 + 文字。标签本身就说清楚了，不用再套 tooltip。 -->
    <v-btn
        v-else-if="!iconOnly"
        v-bind="$attrs"
        variant="text"
        size="small"
        @click.stop="openShareDialog"
    >
        <v-icon start size="small">{{ mdiShareVariant }}</v-icon>{{ t('shareLink') }}
    </v-btn>

    <v-dialog v-model="shareDialogVisible" max-width="420" @keydown.enter.prevent="confirmShareDialog">
        <v-card>
            <v-card-title class="text-h5">{{ t('shareLinkSettings') }}</v-card-title>
            <v-card-text>
                <div class="text-body-2 mb-3 text-medium-emphasis">{{ t('shareLinkSettingsHint') }}</div>
                <div class="mb-1 d-flex justify-space-between align-center">
                    <span class="text-subtitle-2">{{ t('shareExpireIn') }}</span>
                    <span class="text-body-2 text-primary font-weight-medium">{{ shareTtlLabel }}</span>
                </div>
                <div class="share-ttl-control mb-2">
                    <input
                        class="share-ttl-range"
                        type="range"
                        :min="shareTtlMinMinutes"
                        :max="shareTtlMaxMinutes"
                        :step="1"
                        :value="shareForm.ttlMinutes"
                        :aria-label="t('shareExpireIn')"
                        :aria-valuemin="shareTtlMinMinutes"
                        :aria-valuemax="shareTtlMaxMinutes"
                        :aria-valuenow="shareForm.ttlMinutes"
                        :aria-valuetext="shareTtlLabel"
                        @input="onShareTtlInput"
                    >
                    <div class="share-ttl-progress" :style="{ width: shareTtlProgress + '%' }"></div>
                </div>
                <div class="d-flex flex-wrap mb-2" style="gap: 6px;">
                    <v-chip
                        v-for="preset in shareTtlPresets"
                        :key="preset.minutes"
                        small
                        label
                        :variant="shareForm.ttlMinutes !== preset.minutes ? 'outlined' : 'flat'"
                        :color="shareForm.ttlMinutes === preset.minutes ? 'primary' : undefined"
                        class="share-ttl-chip"
                        @click="shareForm.ttlMinutes = preset.minutes"
                    >{{ preset.label }}</v-chip>
                </div>
                <div class="text-caption text-medium-emphasis d-flex justify-space-between mb-4">
                    <span>{{ t('shareTtlMinLabel') }}</span>
                    <span>{{ t('shareTtlMaxLabel') }}</span>
                </div>
                <v-text-field
                    v-model.number="shareForm.maxUses"
                    type="number"
                    min="0"
                    :max="SHARE_MAX_USES_LIMIT"
                    :label="t('shareMaxUses')"
                    :hint="t('shareMaxUsesHint')"
                    persistent-hint
                    density="compact"
                    variant="outlined"
                ></v-text-field>

                <v-text-field
                    v-model="shareForm.password"
                    type="password"
                    autocomplete="new-password"
                    :label="t('sharePasswordLabel')"
                    :hint="t('sharePasswordHint')"
                    persistent-hint
                    density="compact"
                    variant="outlined"
                    class="mt-4"
                ></v-text-field>
            </v-card-text>
            <v-card-actions>
                <v-spacer></v-spacer>
                <v-btn variant="text" @click="shareDialogVisible = false">{{ t('cancel') }}</v-btn>
                <v-btn color="primary" variant="text" :loading="shareUrlLoading" @click="confirmShareDialog">
                    {{ t('generateAndCopy') }}
                </v-btn>
            </v-card-actions>
        </v-card>
    </v-dialog>

    <!-- 分享结果面板：复制与二维码合并后的唯一落点 -->
    <v-dialog v-model="shareResultVisible" max-width="340">
        <v-card>
            <v-card-title class="text-h5 justify-center">{{ t('shareLink') }}</v-card-title>
            <v-card-text class="text-center pa-4">
                <v-progress-circular v-if="shareUrlLoading" indeterminate color="primary" class="my-8"></v-progress-circular>
                <template v-else>
                    <qrcode-vue :value="shareQrUrl" :size="200" level="H" />
                    <div class="text-caption mt-2" style="word-break: break-all;">{{ shareContentUrl }}</div>
                    <div v-if="lastShareMeta" class="text-caption text-medium-emphasis mt-2">
                        {{ t('shareMetaSummary', lastShareMeta) }}
                    </div>
                    <div v-if="lastShareMeta" class="text-caption text-medium-emphasis mt-1">
                        {{ lastShareMeta.openedText }} · {{ t('shareOpenedHint') }}
                    </div>
                </template>
            </v-card-text>
            <v-card-actions>
                <v-spacer></v-spacer>
                <v-btn color="primary" variant="text" :prepend-icon="mdiContentCopy" @click="copyShareLink">{{ t('copyLink') }}</v-btn>
                <v-btn variant="text" @click="shareResultVisible = false">{{ t('close') }}</v-btn>
            </v-card-actions>
        </v-card>
    </v-dialog>
</template>

<style scoped>
.share-ttl-control {
    position: relative;
    height: 28px;
    display: flex;
    align-items: center;
    padding: 0 2px;
}

.share-ttl-control::before {
    content: '';
    position: absolute;
    left: 0;
    right: 0;
    height: 6px;
    border-radius: 999px;
    background: rgba(148, 163, 184, 0.35);
}

.share-ttl-progress {
    position: absolute;
    left: 0;
    height: 6px;
    border-radius: 999px;
    background: var(--v-primary-base, #1976d2);
    pointer-events: none;
    max-width: 100%;
}

.share-ttl-range {
    position: relative;
    z-index: 1;
    width: 100%;
    margin: 0;
    appearance: none;
    -webkit-appearance: none;
    background: transparent;
    height: 28px;
    cursor: pointer;
}

.share-ttl-range:focus {
    outline: none;
}

.share-ttl-range::-webkit-slider-runnable-track {
    height: 6px;
    background: transparent;
    border-radius: 999px;
}

.share-ttl-range::-moz-range-track {
    height: 6px;
    background: transparent;
    border-radius: 999px;
}

.share-ttl-range::-webkit-slider-thumb {
    -webkit-appearance: none;
    appearance: none;
    width: 18px;
    height: 18px;
    margin-top: -6px;
    border-radius: 50%;
    background: var(--v-primary-base, #1976d2);
    border: 2px solid #fff;
    box-shadow: 0 1px 4px rgba(15, 23, 42, 0.35);
}

.share-ttl-range::-moz-range-thumb {
    width: 18px;
    height: 18px;
    border-radius: 50%;
    background: var(--v-primary-base, #1976d2);
    border: 2px solid #fff;
    box-shadow: 0 1px 4px rgba(15, 23, 42, 0.35);
}

.share-ttl-chip {
    cursor: pointer;
}
</style>
