// web-vue3/src/views/modes/BenchWall.vue
<script setup>
// 动作工作台（第 9 个模式，key `bench`）：左边时间流当**输入源**，右边是**动作链**和实时结果。
//
// 和速览的区别（两个都是主从两栏，容易混）：
//   速览是「**读**这条内容」—— 右边是渲染好的完整预览，只读。
//   工作台是「**加工**这条内容」—— 右边是一条可叠多步的动作链，链一变结果立刻重算。
//
// 为什么单独做一个模式而不是塞进标准模式：动作链需要**稳定的第二栏**。
// 挤在卡片里的话，链一长卡片就高得离谱，而时间流的节奏靠的正是「每条卡片一样高」。
//
// ⚠️ 只列**文本条目**。文件条目没有正文（FileReceive 只有 Name/Size/Cache/Expire/Thumbnail/URL，
// 取正文要另发 GET /file/<cache>/<name>），第一版不做 —— 列出来点进去是空的，比不列更糟。
//
// ⚠️ 这个模式**不改数据**。动作结果要落盘只能显式点「另存为新条目」（走现成的 POST /text）。
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { useAppStore } from '@/store/app';
import { useWebSocketStore } from '@/store/websocket';
import { useTheme } from 'vuetify';
import { useI18n } from 'vue-i18n';
import PageToolbar from '@/components/PageToolbar.vue';
import ActionChain from '@/components/bench/ActionChain.vue';
import { decodeHtmlEntities, errorMessage, formatTimestamp } from '@/util.js';
import { postText } from '@/send.js';
import { toast } from '@/plugins/toast';

const app = useAppStore();
const ws = useWebSocketStore();
const theme = useTheme();
const isDark = computed(() => theme.current.value?.dark ?? false);
const { t } = useI18n();

// 宽屏断点 **1024**（和速览一致）：平板那一档也放不下并排两栏。
const isWide = ref(window.innerWidth >= 1024);
function onResize() {
    isWide.value = window.innerWidth >= 1024;
}
onMounted(() => {
    window.addEventListener('resize', onResize);
    // ⚠️ 监听挂 `window` 而不是列表上：焦点通常不在列表里（用户可能在输入框、或刚点完别处），
    // 挂在元素上收不到。这和速览是同一套做法。
    window.addEventListener('keydown', onKeydown);
});

onBeforeUnmount(() => {
    window.removeEventListener('resize', onResize);
    window.removeEventListener('keydown', onKeydown);
});

// 数据源和标准模式/速览**共用**同一个 `app.visibleReceived`（已含搜索过滤）——
// 别再自己 filter 一遍 received，否则搜索框在这个模式里会失效。
const items = computed(() => app.visibleReceived.filter((item) => item.type === 'text'));

// 动作链的输入文本。
//
// ⚠️ **这是唯一的输入源**：点左边列表里的条目 = 「把它的正文填进这里」，
// 而不是「切换到另一种输入模式」。只留一条数据通路 —— 加这个输入框就是为了
// 「想试个动作，却得先往剪贴板发一条」这个调试痛点。
const draft = ref('');

// 列表容器的引用 —— 上下键切换后要把选中项滚进视野，得从它往下找。
const itemsEl = ref(null);

// 当前条目在列表里的下标。
//
// ⚠️ 上一轮把「选中态」删掉是对的（输入框是唯一输入源），但键盘导航需要一个
// 「我现在在哪一条」的位置 —— 所以它回来了，只是**只服务于上下键和视觉反馈**，
// 不再是「另一种输入模式」。
const activeIndex = ref(-1);

// 服务端存的是 HTML 实体编码过的正文（`<` 之类），填进来之前要还原回原文。
// 全站唯一实现在 util.js 的 decodeHtmlEntities —— 别在这里再写一份。
function fillFrom(item) {
    draft.value = decodeHtmlEntities(item.content || '');
}

/** 选中第 index 条：填进输入框 + 记下位置 + 把它滚进视野。 */
function selectIndex(index) {
    const list = items.value;
    if (index < 0 || index >= list.length) {
        return; // 到头 / 到尾就不动
    }
    activeIndex.value = index;
    fillFrom(list[index]);
    // 选中项得留在视野里，否则按住不放它就跑出屏幕了。
    // `block: 'nearest'` —— 只滚「刚好够看见」那一点，不会把整列翻过去。
    nextTick(() => {
        const rows = itemsEl.value?.querySelectorAll('.bench-wall__item');
        rows?.[index]?.scrollIntoView({ block: 'nearest' });
    });
}

/**
 * 上下键切换输入源条目。
 *
 * ⚠️ **焦点在输入框 / 可编辑元素里时不接管** —— 那时上下键是**移光标**，用户正在编辑文本。
 * 速览那边可以无脑接管（它的搜索框是单行的，上下键本来没别的含义），这里不行：
 * 动作台的输入框是**多行 textarea**。
 */
function onKeydown(event) {
    if (event.key !== 'ArrowUp' && event.key !== 'ArrowDown') {
        return;
    }
    const el = event.target;
    if (el && (el.tagName === 'TEXTAREA' || el.tagName === 'INPUT' || el.isContentEditable)) {
        return;
    }
    // ⚠️ 必须拦掉默认动作：方向键默认是**滚容器**，不拦就会「换了条目 + 页面也滚了」。
    event.preventDefault();
    const delta = event.key === 'ArrowDown' ? 1 : -1;
    selectIndex(activeIndex.value < 0 ? 0 : activeIndex.value + delta);
}

// 首次有内容时自动填第一条 —— 一进这个模式就有东西可试。
// ⚠️ 只在**输入框还空着**时填，否则会把用户正在打的内容冲掉。
watch(
    items,
    (list) => {
        if (!draft.value && list.length) {
            activeIndex.value = 0;
            fillFrom(list[0]);
        }
    },
    { immediate: true },
);

function summary(item) {
    const text = decodeHtmlEntities(item.content || '').replace(/\s+/g, ' ').trim();
    return text || t('shareHistoryText');
}

/** 把动作结果另存为一条**新**条目。走的是现成的 `POST /text`，后端零改动。 */
async function saveAsNew(content) {
    const body = String(content ?? '');
    if (!body) {
        return;
    }
    try {
        // ⚠️ 这条 POST 的**唯一**定义在 `src/send.js`（外壳的分享桥走的是同一个函数）。
        // 这里原来也是手写的一份、同样漏了 `?client=`。
        await postText({ room: ws.room, text: body });
        toast(t('actionSaveAsNewDone'));
    } catch (err) {
        toast(errorMessage(err) || t('sendFailed'));
    }
}
</script>

<template>
    <div class="bench-wall" :class="{ 'bench-wall--dark': isDark, 'bench-wall--wide': isWide }">
        <PageToolbar />

        <div class="bench-wall__body">
            <!-- 左：输入源 -->
            <aside class="bench-wall__list">
                <div class="bench-wall__list-head">
                    <v-icon size="14">mdi-inbox-arrow-down-outline</v-icon>
                    <span>{{ t('benchSourceTitle') }}</span>
                    <span class="bench-wall__count">{{ items.length }}</span>
                </div>

                <div ref="itemsEl" class="bench-wall__items">
                    <button
                        v-for="(item, index) in items"
                        :key="item.id"
                        type="button"
                        class="bench-wall__item"
                        :class="{ 'bench-wall__item--active': index === activeIndex }"
                        @click="selectIndex(index)"
                    >
                        <span class="bench-wall__item-time">{{ formatTimestamp(item.timestamp) }}</span>
                        <span class="bench-wall__item-text">{{ summary(item) }}</span>
                    </button>

                    <div v-if="!items.length" class="bench-wall__empty">
                        {{ t('benchEmpty') }}
                    </div>
                </div>
            </aside>

            <!-- 右：输入框 + 动作链 + 结果。
                 输入框放在这一栏的**顶部**而不是左栏 —— 左栏那点宽度写长文本太憋屈，
                 而右边本来就是「工作区」（输入 → 加工 → 结果），三样在同一条竖线上。 -->
            <section class="bench-wall__panel">
                <textarea
                    v-model="draft"
                    class="bench-wall__draft"
                    :placeholder="t('benchDraftPlaceholder')"
                    spellcheck="false"
                ></textarea>

                <ActionChain v-if="draft" class="bench-wall__chain" :text="draft" @save-as-new="saveAsNew" />
                <div v-else class="bench-wall__empty bench-wall__empty--panel">
                    {{ t('benchDraftEmpty') }}
                </div>
            </section>
        </div>
    </div>
</template>

<style scoped>
.bench-wall {
    display: flex;
    flex-direction: column;
    /* dvh 而不是 vh：移动端地址栏收起/展开会改可视高度，用 vh 会让底部被裁掉 */
    height: 100dvh;
    overflow: hidden;
}

.bench-wall__body {
    flex: 1;
    min-height: 0;
    display: flex;
    flex-direction: column;
    gap: 10px;
    padding: 10px 12px 14px;
}

/* ⚠️ 两处 CSS 一起才能让内部真的滚起来：
   容器给 grid/flex 项 minmax(0,1fr)（或 min-height:0），**子项**还要再写 min-height:0 ——
   否则子项的默认 min-height:auto 会把它撑到内容高度，滚动条永远不出现。 */
.bench-wall__list {
    display: flex;
    flex-direction: column;
    min-height: 0;
    /* 窄屏：列表只占三成 —— 这一屏的主体是右边的「输入 → 加工 → 结果」，
       列表只是取数据的入口。38% 会把工作区挤得只剩一半，动作链和结果都看不全。 */
    flex: 0 0 30%;
    border: 1px solid rgba(148, 163, 184, 0.26);
    border-radius: 16px;
    background: rgba(255, 255, 255, 0.9);
    overflow: hidden;
}

.bench-wall__panel {
    flex: 1;
    min-height: 0;
    display: flex;
    flex-direction: column;
    border: 1px solid rgba(148, 163, 184, 0.26);
    border-radius: 16px;
    background: rgba(255, 255, 255, 0.9);
    padding: 12px;
    overflow: hidden;
}

/* 宽屏：左右两栏 */
.bench-wall--wide .bench-wall__body {
    flex-direction: row;
}

.bench-wall--wide .bench-wall__list {
    flex: 0 0 320px;
}

.bench-wall__list-head {
    display: flex;
    align-items: center;
    gap: 6px;
    padding: 9px 12px;
    border-bottom: 1px solid rgba(148, 163, 184, 0.26);
    font-size: 0.6875rem;
    font-weight: 700;
    letter-spacing: 0.04em;
    color: rgba(71, 85, 105, 0.75);
    flex: 0 0 auto;
}

.bench-wall__count {
    margin-left: auto;
    font-weight: 500;
}

/* 手输的调试输入框 —— 在**右栏顶部**。固定高度 + 允许纵向拖拽：
   长文本要能看全几行，但不能把下面的动作链挤没。
   `color: inherit` 是必须的：textarea 默认是黑色，暗色主题下会看不见。
   背景用 transparent（跟着面板走），这样暗色主题不必再写一条覆盖规则。 */
.bench-wall__draft {
    flex: 0 0 auto;
    height: 88px;
    min-height: 44px;
    resize: vertical;
    border: 1px solid rgba(148, 163, 184, 0.42);
    border-radius: 10px;
    background: transparent;
    padding: 8px 10px;
    margin-bottom: 10px;
    font-family: inherit;
    font-size: 0.75rem;
    line-height: 1.55;
    color: inherit;
    outline: none;
}

.bench-wall__draft:focus {
    border-color: rgb(var(--v-theme-primary));
}

.bench-wall__draft::placeholder {
    /* 主题变量：写死的深灰在暗色主题下看不见 */
    color: rgba(var(--v-theme-on-surface), 0.4);
}

/* 动作链占满输入框剩下的高度（它内部再分「链」和「结果」两块） */
.bench-wall__chain {
    flex: 1;
    min-height: 0;
}

.bench-wall__items {
    flex: 1;
    min-height: 0;
    overflow-y: auto;
    padding: 6px;
}

.bench-wall__item {
    display: flex;
    align-items: baseline;
    gap: 8px;
    width: 100%;
    text-align: left;
    padding: 7px 9px;
    border: 1px solid transparent;
    border-radius: 9px;
    background: transparent;
    cursor: pointer;
    font-size: 0.75rem;
    color: inherit;
    transition: background-color 0.15s ease, border-color 0.15s ease;
}

.bench-wall__item:hover {
    background: rgba(14, 165, 233, 0.07);
}

/* 当前条目（点选的，或上下键选中的那条）。它同时是「输入框里那段文字来自哪」的指示 ——
   没有这个高亮，用上下键切换时界面上看不出选中的是哪一条。 */
.bench-wall__item--active {
    background: rgba(var(--v-theme-primary), 0.12);
    border-color: rgba(var(--v-theme-primary), 0.45);
}

.bench-wall__item-time {
    flex: 0 0 auto;
    font-size: 0.625rem;
    color: rgba(71, 85, 105, 0.7);
    font-variant-numeric: tabular-nums;
}

.bench-wall__item-text {
    flex: 1;
    min-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}

.bench-wall__empty {
    padding: 24px 8px;
    text-align: center;
    font-size: 0.75rem;
    color: rgba(71, 85, 105, 0.7);
}

.bench-wall__empty--panel {
    margin: auto;
}

.bench-wall--dark .bench-wall__list,
.bench-wall--dark .bench-wall__panel {
    background: rgba(15, 23, 42, 0.9);
    border-color: rgba(71, 85, 105, 0.72);
}

.bench-wall--dark .bench-wall__list-head,
.bench-wall--dark .bench-wall__item-time,
.bench-wall--dark .bench-wall__empty {
    color: rgba(226, 232, 240, 0.72);
}
</style>

// web/src/modes/BenchWall.tsx
import { useEffect, useMemo, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Box, Stack, Typography } from '@mui/material';
import { PageToolbar } from '@/components/AppShell/PageToolbar';
import { ActionChain } from '@/components/bench/ActionChain';
import { MdiIcon } from '@/components/ui/MdiIcon';
import { useAppStore, selectVisibleReceived, type ReceivedItem } from '@/stores/appStore';
import { useWebSocketStore } from '@/stores/wsStore';
import { toast } from '@/stores/toastStore';
import { decodeHtmlEntities, errorMessage, formatTimestamp } from '@/lib/util';
import { postText } from '@/services/send';

/**
 * 动作工作台 —— 从 web-vue3/src/views/modes/BenchWall.vue 移植。
 *
 * 和速览的区别（两个都是主从两栏）：速览是「**读**这条内容」（右侧只读预览）；
 * 工作台是「**加工**这条内容」（右侧是可叠多步的动作链 + 实时结果）。
 *
 * ⚠️ 只列**文本条目**（文件条目没有正文，取正文要另发请求，第一版不做）。
 * ⚠️ 这个模式**不改数据** —— 结果要落盘只能显式点「另存为新条目」（走现成的 `POST /text`）。
 * ⚠️ 上下键切换时，**焦点在输入框 / 可编辑元素里就不接管**（那里方向键是移光标）。
 */
export default function BenchWall() {
    const { t } = useTranslation();
    const itemsRef = useRef<HTMLDivElement | null>(null);

    const received = useAppStore((s) => s.received);
    const searchQuery = useAppStore((s) => s.searchQuery);

    // 数据源与标准模式/速览**共用** `selectVisibleReceived`（已含搜索过滤）。
    const items = useMemo(
        () => selectVisibleReceived({ received, searchQuery }).filter((item) => item.type === 'text'),
        [received, searchQuery],
    );

    const [draft, setDraft] = useState('');
    const [activeIndex, setActiveIndex] = useState(-1);

    const [isWide, setIsWide] = useState(() => window.innerWidth >= 1024);
    useEffect(() => {
        const onResize = () => setIsWide(window.innerWidth >= 1024);
        window.addEventListener('resize', onResize);
        return () => window.removeEventListener('resize', onResize);
    }, []);

    // 服务端存的是 HTML 实体编码过的正文，填进来之前要还原回原文。
    const fillFrom = (item: ReceivedItem) => setDraft(decodeHtmlEntities(String(item.content || '')));

    const selectIndex = (index: number) => {
        if (index < 0 || index >= items.length) return;
        setActiveIndex(index);
        fillFrom(items[index]);
        requestAnimationFrame(() => {
            itemsRef.current?.querySelectorAll('.bench-wall__item')[index]?.scrollIntoView({ block: 'nearest' });
        });
    };

    // 首次有内容时自动填第一条 —— 一进这个模式就有东西可试（只在输入框还空着时填）。
    useEffect(() => {
        if (!draft && items.length) {
            setActiveIndex(0);
            fillFrom(items[0]);
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [items]);

    useEffect(() => {
        const onKeyDown = (event: KeyboardEvent) => {
            if (event.key !== 'ArrowUp' && event.key !== 'ArrowDown') return;
            const el = event.target as HTMLElement | null;
            // ⚠️ 焦点在输入框 / 可编辑元素里时不接管（那里方向键是移光标）。
            if (el && (el.tagName === 'TEXTAREA' || el.tagName === 'INPUT' || el.isContentEditable)) return;
            event.preventDefault();
            const delta = event.key === 'ArrowDown' ? 1 : -1;
            selectIndex(activeIndex < 0 ? 0 : activeIndex + delta);
        };
        window.addEventListener('keydown', onKeyDown);
        return () => window.removeEventListener('keydown', onKeyDown);
    });

    const saveAsNew = async (content: string) => {
        const body = String(content ?? '');
        if (!body) return;
        try {
            await postText({ room: useWebSocketStore.getState().room, text: body });
            toast(t('actionSaveAsNewDone'));
        } catch (error) {
            toast(errorMessage(error) || t('sendFailed'));
        }
    };

    const summary = (item: ReceivedItem) => decodeHtmlEntities(String(item.content || '')).replace(/\s+/g, ' ').trim() || t('shareHistoryText');

    return (
        <Box sx={{ display: 'flex', flexDirection: 'column', height: '100dvh', overflow: 'hidden' }}>
            <PageToolbar />
            <Box sx={{ flex: 1, minHeight: 0, display: 'flex', flexDirection: isWide ? 'row' : 'column', gap: 1.25, p: '10px 12px 14px' }}>
                {/* 左：输入源 */}
                <Box
                    component="aside"
                    sx={{
                        display: 'flex',
                        flexDirection: 'column',
                        minHeight: 0,
                        flex: isWide ? '0 0 320px' : '0 0 30%',
                        border: 1,
                        borderColor: 'divider',
                        borderRadius: 2,
                        overflow: 'hidden',
                    }}
                >
                    <Stack direction="row" alignItems="center" spacing={0.75} sx={{ px: 1.5, py: 1, borderBottom: 1, borderColor: 'divider', flexShrink: 0 }}>
                        <MdiIcon name="mdi-inbox-arrow-down-outline" size={14} />
                        <Typography variant="caption" sx={{ fontWeight: 700, letterSpacing: '0.04em' }}>{t('benchSourceTitle')}</Typography>
                        <span style={{ flex: 1 }} />
                        <Typography variant="caption" color="text.secondary">{items.length}</Typography>
                    </Stack>
                    <Box ref={itemsRef} sx={{ flex: 1, minHeight: 0, overflowY: 'auto', p: 0.75 }}>
                        {items.map((item, index) => (
                            <Box
                                key={item.id}
                                component="button"
                                type="button"
                                className="bench-wall__item"
                                onClick={() => selectIndex(index)}
                                sx={{
                                    display: 'flex',
                                    alignItems: 'baseline',
                                    gap: 1,
                                    width: '100%',
                                    textAlign: 'left',
                                    px: 1.125,
                                    py: 0.875,
                                    border: 1,
                                    borderColor: index === activeIndex ? 'primary.main' : 'transparent',
                                    borderRadius: 1.25,
                                    background: index === activeIndex ? 'action.selected' : 'none',
                                    cursor: 'pointer',
                                    fontSize: '0.75rem',
                                    color: 'inherit',
                                }}
                            >
                                <Typography variant="caption" sx={{ flex: '0 0 auto', fontSize: '0.625rem', color: 'text.secondary' }}>
                                    {formatTimestamp(item.timestamp)}
                                </Typography>
                                <Typography variant="caption" noWrap sx={{ flex: 1, minWidth: 0 }}>{summary(item)}</Typography>
                            </Box>
                        ))}
                        {!items.length && (
                            <Typography variant="caption" color="text.secondary" sx={{ display: 'block', textAlign: 'center', py: 3 }}>
                                {t('benchEmpty')}
                            </Typography>
                        )}
                    </Box>
                </Box>

                {/* 右：输入框 + 动作链 + 结果 */}
                <Box
                    component="section"
                    sx={{ flex: 1, minHeight: 0, display: 'flex', flexDirection: 'column', border: 1, borderColor: 'divider', borderRadius: 2, p: 1.5, overflow: 'hidden' }}
                >
                    <Box
                        component="textarea"
                        value={draft}
                        onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setDraft(e.target.value)}
                        placeholder={t('benchDraftPlaceholder')}
                        spellCheck={false}
                        sx={{
                            flex: '0 0 auto',
                            height: 88,
                            minHeight: 44,
                            resize: 'vertical',
                            border: 1,
                            borderColor: 'divider',
                            borderRadius: 1.25,
                            background: 'transparent',
                            p: '8px 10px',
                            mb: 1.25,
                            fontFamily: 'inherit',
                            fontSize: '0.75rem',
                            lineHeight: 1.55,
                            color: 'inherit',
                            outline: 'none',
                        }}
                    />
                    {draft ? (
                        <Box sx={{ flex: 1, minHeight: 0 }}>
                            <ActionChain text={draft} onSaveAsNew={(content) => void saveAsNew(content)} />
                        </Box>
                    ) : (
                        <Typography variant="caption" color="text.secondary" sx={{ m: 'auto' }}>{t('benchDraftEmpty')}</Typography>
                    )}
                </Box>
            </Box>
        </Box>
    );
}
